[build]
builder = "nixpacks"

[start]
cmd = "mkdir -p storage/framework/sessions storage/framework/views storage/framework/cache && php artisan migrate --force --no-interaction && /app/.nixpacks/bin/start-server"
