[build]
builder = "nixpacks"

[phases.setup]
nixPkgs = ["php82", "php82Extensions.gd", "php82Extensions.zip", "php82Extensions.pdo_mysql"]

[phases.prestart]
cmds = [
    "mkdir -p storage/framework/sessions storage/framework/views storage/framework/cache",
    "php artisan config:clear",
    "php artisan route:clear",
    "php artisan view:clear",
    "php artisan migrate --force",
    "php artisan db:seed --force"
]
